project_id = "bmwjaulhlbmnfptuszoj"
[functions.verify-doc-password]
verify_jwt = false

[functions.docs-content]
verify_jwt = false



[functions.preview-transactional-email]
verify_jwt = false



[functions.linkedin-company-feed]
verify_jwt = false

[functions.submit-rfq]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false
