// ─── APPEND THESE ENTRIES TO THE END OF THE products[] ARRAY IN src/data/products.ts ───
// Add these BEFORE the closing ]; of the products array
// Don't forget to add a comma after the last existing entry (ni-nta-magnetic)

  {
    id: "co-nta-agarose",
    name: "Co-NTA Agarose",
    subtitle: "Affinity · Cobalt · His-tagged Proteins",
    chromatographyType: "affinity",
    exchangerType: null,
    status: "available",
    ligand: "Co-NTA",
    matrix: "6% cross-linked agarose",
    particleSizeRange: "45–165 µm",
    particleSizeD50V: "~90 µm",
    ionicCapacity: null,
    dbc: "~20",
    dbcUnit: "mg His-tagged protein/mL",
    flowSpec: "400–700 cm/h, 0.1 MPa",
    maxFlowVelocity: "700 cm/hr",
    phCIP: "2–14",
    phOperational: "3–12",
    chemicalStability: "0.01 M HCl, 0.1 M NaOH, 8 M urea",
    storage: "4–30°C, 20% Ethanol",
    deliveryTime: "2–3 weeks",
    packSizes: [
      { catNo: "CO01", size: "5 mL" },
      { catNo: "CO02", size: "25 mL" },
      { catNo: "CO03", size: "50 mL" },
      { catNo: "CO04", size: "100 mL" },
      { catNo: "CO05", size: "250 mL" },
    ],
    applications: [
      "Lower non-specific binding than Ni-NTA for sensitive targets",
      "His-tag purification where higher selectivity is required",
      "Alternative IMAC metal for reduced co-purification of host proteins",
    ],
    flowVariant: "standard" as const,
    tags: ["BioProcess", "Affinity", "His-tag", "Cobalt"],
  },
  {
    id: "4pct-agarose",
    name: "4% Agarose Resin",
    subtitle: "Size Exclusion · Molecular Sieving",
    chromatographyType: "sec",
    exchangerType: null,
    status: "available",
    ligand: "None (underivatised)",
    matrix: "4% spherical cross-linked agarose",
    particleSizeRange: "45–165 µm",
    particleSizeD50V: "~90 µm",
    ionicCapacity: null,
    dbc: "N/A",
    dbcUnit: "(size exclusion)",
    flowSpec: "200–500 cm/h",
    maxFlowVelocity: "500 cm/hr",
    phCIP: "2–14",
    phOperational: "3–13",
    chemicalStability: "1.0 M NaOH, 8 M urea, 70% EtOH",
    storage: "4–30°C, 20% Ethanol",
    deliveryTime: "2–3 weeks",
    packSizes: withPrefix("SE"),
    applications: [
      "Group separation and buffer exchange",
      "Desalting of protein preparations",
      "Molecular sieving for proteins and EVs",
    ],
    flowVariant: "standard" as const,
    tags: ["SEC", "Buffer exchange", "Desalting"],
  },
  {
    id: "protein-a-agarose",
    name: "Protein A Agarose",
    subtitle: "Affinity · mAb Capture · IgG/IgM",
    chromatographyType: "affinity",
    exchangerType: null,
    status: "pipeline",
    ligand: "Protein A (recombinant)",
    matrix: "6% cross-linked agarose",
    particleSizeRange: "45–165 µm",
    particleSizeD50V: "~90 µm",
    ionicCapacity: null,
    dbc: "~20",
    dbcUnit: "mg IgG/mL (projected)",
    flowSpec: "300–700 cm/h",
    maxFlowVelocity: "700 cm/hr",
    phCIP: "2–14",
    phOperational: "3–11",
    chemicalStability: "0.1 M NaOH (limited cycles)",
    storage: "4–8°C, 20% Ethanol",
    deliveryTime: "TBD",
    packSizes: [
      { catNo: "PA01", size: "1 mL" },
      { catNo: "PA02", size: "5 mL" },
      { catNo: "PA03", size: "25 mL" },
    ],
    applications: [
      "Single-step monoclonal antibody capture",
      "IgG purification from cell culture supernatant",
      "Platform process for mAb therapeutics",
    ],
    flowVariant: "standard" as const,
    tags: ["Affinity", "Pipeline", "mAb", "Protein A"],
  },
